alfabeto = dict()

string = str(input("Digite o texto: "))

for alfabeto in string.lower():
    print(alfabeto)
    len(alfabeto)
    alfabeto.count("a")
    alfabeto.count("b")
    alfabeto.count("c")
    alfabeto.count("d")
    alfabeto.count("e")
    alfabeto.count("f")
    alfabeto.count("g")
    alfabeto.count("h")
    alfabeto.count("i")
    alfabeto.count("j")
    alfabeto.count("k")
    alfabeto.count("l")
    alfabeto.count("m")
    alfabeto.count("n")
    alfabeto.count("o")
    alfabeto.count("p")
    alfabeto.count("q")
    alfabeto.count("r")
    alfabeto.count("s")
    alfabeto.count("t")
    alfabeto.count("u")
    alfabeto.count("v")
    alfabeto.count("w")
    alfabeto.count("x")
    alfabeto.count("y")
    alfabeto.count("z")
   